### ISSUE TITLE
Rightarrow => not understood (correctly)

### ISSUE THREAD

**Issue by andreasabel** [hunt-framework/hayoo#34]
Parses, but no results: `MonadState s m => m s`
http://hayoo.fh-wedel.de/?query=MonadState+s+m+%3D%3E+m+s
Fails to parse: `MonadState s m => s -> m ()`
http://hayoo.fh-wedel.de/?query=MonadState+s+m+%3D%3E+s+-%3E+m+%28%29

**Comment by chrisreu** [comment]
Seems to be done now? @sebastian-philipp @alexbiehl

**Comment by alexbiehl** [comment]
Same as #38 and #39.

Chris Reumann <notifications@github.com> schrieb am Mo., 25. Mai 2015 um
19:52 Uhr:

**Comment by andreasabel** [comment]
Yes, seems to work.
