### ISSUE TITLE
Cannot match on simple signature

### ISSUE THREAD

**Issue by crockeea** [hunt-framework/hayoo#38]
Searching for the `join` function, I typed in `m (m a) -> m a`
http://hayoo.fh-wedel.de/?query=m+%28m+a%29+-%3E+m+a
but got no results. I'm pretty sure this should work, since that is precisely the signature of `join`.

**Comment by chrisreu** [comment]
@sebastian-philipp @alexbiehl 

This also seems to work in the current version?

**Comment by alexbiehl** [comment]
Same as #39.

Chris Reumann <notifications@github.com> schrieb am Mo., 25. Mai 2015 um
19:50 Uhr:
