### ISSUE TITLE
forall in signatures

### ISSUE THREAD

**Issue by NCrashed** [hunt-framework/hayoo#39]
Search query: zipM

Displayed result: zipMono :: a -> a -> a) -> v -> v -> v 
Expected result: zipMono :: Proxy c -> (forall a. c a => a -> a -> a) -> v -> v -> v

**Comment by chrisreu** [comment]
@sebastian-philipp @alexbiehl

Looks like this is already fixed?

**Comment by alexbiehl** [comment]
Yes, an older version was deployed back then.

Chris Reumann <notifications@github.com> schrieb am Mo., 25. Mai 2015 um
19:49 Uhr:
