### ISSUE TITLE
Order results by library popularity

### ISSUE THREAD

**Issue by nikita-volkov** [hunt-framework/hayoo#41]
Some recent updates made Hayoo searching very inconvenient, since now it often outputs anything but the expected results. For instance, [searching for `evalState`](http://hayoo.fh-wedel.de/?query=evalState) does not even include the obviously expected result from the "transformers" package in the first page.

**Comment by nikomi** [comment]
I want to support this request and suggest to sort `base` packages first.

**Comment by alexbiehl** [comment]
Hey, 

Thank you for reporting the issue. Iam working on a package rank implementation for the new indexer. So the packages most dependent upon get a higher score.

I am ready next week. In the meantime, I will deploy an older Version later today. Sorry for the inconveniences.

----- Ursprüngliche Nachricht -----
Von: "nikomi" <notifications@github.com>
Gesendet: ‎13.‎03.‎2015 09:48
An: "hunt-framework/hayoo" <hayoo@noreply.github.com>
Betreff: Re: [hayoo] Order results by library popularity (#41)

I want to support this request and suggest to sort base packages first.

**Comment by nikita-volkov** [comment]
Thanks

**Comment by jprider63** [comment]
Have you redeployed the old version? I'm still getting bad results.

**Comment by chrisreu** [comment]
This is fixed now, right?

**Comment by alexbiehl** [comment]
Yes, fixed in
https://github.com/hunt-framework/hayoo/commit/8389c25524c3174ffb1406b83cf0c2db76330998

Chris Reumann <notifications@github.com> schrieb am Mo., 25. Mai 2015 um
19:48 Uhr:
