### ISSUE TITLE
"more" at end of function synopsis preview does not work

### ISSUE THREAD

**Issue by ocramz** [hunt-framework/hayoo#49]
Rather than expanding to the whole function docstring, it _removes_ any function description, leaving only the type signature.

Observed on Chrome Version 51.0.2704.84 (64-bit), OSX 10.9.5

**Comment by noobymatze** [comment]
Hi ocramz, thanks for telling us. As soon as I get some time, I'll take a look.

**Comment by alexbiehl** [comment]
I just redeployed Hayoo. It is working now.

**Comment by ocramz** [comment]
@alexbiehl @noobymatze Great! It works like a charm now; nice revamp too. thank you : )
